// Barrel re-exports — all existing `import { xxxApi } from '@/api'` continue to work
export { authApi } from './modules/auth'
export { userApi } from './modules/user'
export { symptomApi } from './modules/patient/diary'
export { commentApi } from './modules/patient/comment'
export { capsuleApi } from './modules/patient/capsule'
export { treeHoleApi } from './modules/patient/treeHole'
export { resourceApi, recommendApi } from './modules/patient/resource'
export { reportApi } from './modules/patient/report'
export { aiApi } from './modules/patient/ai'
export { chatApi } from './modules/patient/chat'
export { roomApi, themeApi } from './modules/patient/room'
export { doctorApi } from './modules/doctor/index'
export { doctorChatApi } from './modules/doctor/chat'
export { adminApi } from './modules/admin/index'
export { profileApi } from './modules/patient/profile'
export { assessmentApi } from './modules/patient/assessment'
export { meditationApi } from './modules/patient/meditation'
export { dashboardApi } from './modules/patient/dashboard'
export { notificationApi } from './modules/notification'
export { crisisApi } from './modules/doctor/crisis'
export { schedulingApi } from './modules/scheduling'
export { treatmentApi } from './modules/treatment'
export { analyticsApi } from './modules/analytics'
